version: 2.1

jobs:
  test_api:
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_NAME: lumigula
          DB_USERNAME: posgtres
          DB_PASSWORD: password
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_DB: lumigula
          POSTGRES_USER: posgtres
          POSTGRES_PASSWORD: password

    working_directory: ~/lumigula

    steps:
      - checkout

      # restore gem from cache
      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "~/lumigula/api/Gemfile.lock" }}
            - gem-cache-v1-
          working_directory: ~/lumigula/api

      # gem install
      - run:
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
          working_directory: ~/lumigula/api

      - save_cache:
          key: gem-cache-v1-{{ checksum "~/lumigula/api/Gemfile.lock" }}
          paths:
            - ~/lumigula/api/vendor/bundle
          working_directory: ~/lumigula/api

      # Database setup
      - run:
          command: bundle exec rails db:create
          working_directory: ~/lumigula/api
      - run:
          command: bundle exec rails db:migrate
          working_directory: ~/lumigula/api

      - run:
          name: create directory to store test results
          command: mkdir /tmp/test-results
          working_directory: ~/lumigula/api

      # run tests
      - run:
          name: RSpec
          command: |
            bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings) \
              || (printf "====== RETRYING...\n\n\n"; bundle exec rspec --only-failures)
          working_directory: ~/lumigula/api

      # collect lumigularts
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - store_artifacts:
          path: /home/circleci/lumigula/tmp/screenshots

  test_front:
    docker:
      - image: circleci/node:14.4.0
        environment:
          NODE_ENV: test

    working_directory: ~/lumigula

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/lumigula/front/package.json" }}
          working_directory: ~/lumigula/front
      - run:
          name: install-packages
          command: yarn install
          working_directory: ~/lumigula/front
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "~/lumigula/front/package.json" }}
          working_directory: ~/lumigula/front
      - run:
          name: test
          command: yarn run test
          working_directory: ~/lumigula/front

workflows:
  version: 2
  test:
    jobs:
      - test_api:
          filters:
            branches:
              ignore: main
      - test_front:
          filters:
            branches:
              ignore: main
