default: &default
  adapter: postgresql
  encoding: unicode
  host: db # サービス名（docker-compose.yml）
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
